[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Added so stack slot on the test can exceed 16
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC}"
